stages:
  data_ingestion:
    cmd: python src/animalClassifier/pipeline/stage_01_data_ingestion.py 
    deps:
      - src/animalClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/animals

  training:
    cmd: python src/animalClassifier/pipeline/stage_02_training.py
    deps:
      - src/animalClassifier/pipeline/stage_02_training.py
      - artifacts/data_ingestion/animals
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/training/vgg16_model.h5

  